apiVersion: apps/v1
kind: Deployment
metadata:
  name: portstats-deployment
  labels:
    deployment: portstats-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portstats
  template:
    metadata:
      labels:
        app: portstats
    spec:
      containers:
      - name: portstats-app
        image: tqhuy812/portstats-app:v1
        stdin: true
        tty: true
        env:
        - name: ONOS_IP
          value: "onos-ext"
---
apiVersion: v1
kind: Service
metadata:
  name: portstats-ext
  labels:
    sdn: portstats-ext
spec:
  type: NodePort
  ports:
  - name: rest
    port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    app: portstats
