apiVersion: v1
kind: Service
metadata:
  name: onos-ext
  labels:
    sdn: onos-ext
spec:
  type: NodePort
  ports:
  - name: gui
    port: 8181
    nodePort: 30004
  - name: openflow
    port: 6653
    targetPort: 6653
    nodePort: 30006
  selector:
    sdn-controller: onos
