apiVersion: v1
kind: Service
metadata:
  name: onos-ext
  labels:
    sdn: onos-ext
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 8101
    targetPort: 8101
  - name: gui
    port: 8181
    nodePort: 30004
  - name: openflow
    port: 6653
    targetPort: 6653
  externalIPs:
    - 192.168.99.100
  selector:
    sdn-controller: onos
