apiVersion: v1
kind: Service
metadata:
  name: onos-ext
  labels:
    sdn: onos-ext
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 8101
    targetPort: 8101
    nodePort: 30101
  - name: openflow
    port: 6653
    targetPort: 6653
    nodePort: 30653
  selector:
    sdn-controller: onos
